TEST_VALUE:
  name: 'dev_cookie'
FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a40a242efb76500c
  FEISHU_APP_SECRET: FWEFLf7s5YQ2ADN15HV00gviI3fzmNjc
APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
USER_TOKEN_CACHE_KEY: USER_TOKEN_CACHE_KEY
USER_REFRESH_TOKEN_CACHE_KEY: USER_REFRESH_TOKEN_CACHE_KEY
# MONGODB_CONFIG:
#   # name: 'fast_gateway_test' # 自定义次数据库链接名称
#   type: mongodb # 数据库链接类型
#   # url: 'mongodb://127.0.0.1:27017' # 数据库链接地址
#   host: '127.0.0.1'
#   port: 27017
#   username: '' # 数据库链接用户名
#   password: '' # 数据库链接密码
#   database: 'fast_gateway_test' # 数据库名
#   entities: 'mongo' # 自定义加载类型
#   logging: false # 数据库打印日志
#   synchronize: true # 是否开启同步数据表功能
MONGODB_CONFIG:
  name: 'fast_gateway_monogo'
  type: mongodb # 数据库链接类型
  url: 'mongodb://::1:27017'
  username: '' # 数据库链接用户名
  password: '' # 数据库链接密码
  database: 'fast_gateway_test' # 数据库名
  entities: 'mongo' # 自定义加载类型
  logging: false # 数据库打印日志
  synchronize: true # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: 'fast_gateway_mysql'
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'rootroot'
  database: 'fast_gateway_mysql'
  entities: 'mysql' # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true
REDIS_CONFIG:
  host: 'localhost' # redis 链接
  port: 6379 # redis 端口
  auth: '' # redis 连接密码
  db: 1 # redis 数据库
