export const data = {
  assets: [],
  styles: [
    {
      selectors: [],
      selectorsAdd: ':root',
      style: {
        '--mdc-theme-info': '#0288d1',
        '--mdc-theme-error': '#d32f2f',
        '--mdc-theme-primary': '#9c27b0',
        '--mdc-theme-success': '#2e7d32',
        '--mdc-theme-warning': '#ed6c02',
        '--mdc-theme-secondary': '#1976d2',
      },
    },
    {
      selectors: [
        {
          name: 'ctejq',
          protected: 1,
        },
      ],
      style: {
        'background-image': 'linear-gradient(#9E9070 0%, #9E9070 100%)',
      },
    },
  ],
  pages: [
    {
      frames: [
        {
          component: {
            type: 'wrapper',
            stylable: [],
            classes: [
              {
                name: 'ctejq',
                protected: 1,
              },
            ],
            __classId: 'ctejq',
            pageLayout: {
              showFooter: false,
              showHeader: false,
            },
          },
        },
      ],
      id: 'O7CEtZbft9MGQJ0g',
      name: 'HOME12',
      type: 'main',
      seoForm: {
        pageurl: '/O7CEtZbft9MGQJ0g.html',
        pagedesc: '',
        pagetitle: '',
      },
      basicForm: {
        name: 'HOME0',
        isHome: false,
        isMenuHidden: false,
        pagePassword: '',
        specificUser: 1,
        authorization: 1,
      },
      pageColorForm: {
        pageurl: '/O7CEtZbft9MGQJ0g.html',
        pagedesc: '',
        pageColor: {
          color: '#1976d2',
          index: null,
          imgSrc: '',
          values: [
            '#1976d2',
            '#9c27b0',
            '#d32f2f',
            '#ed6c02',
            '#0288d1',
            '#2e7d32',
          ],
          saturation: 1,
        },
        pagetitle: '',
        pageIndColor: false,
      },
      pageLayoutForm: {
        state: [0, 0, 0, 0],
        pgIndBg: false,
        deviceBg: [
          {
            bgImg: [],
            bgPos: 'center center',
            bgSize: 'auto',
            pgColor: {
              type: 'pure',
              angle: 90,
              active: 0,
              colors: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              values: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              trigger: false,
              linearangle: [0, 100],
              linearcolor: ['#777777', '#000000'],
            },
            bgAttach: 'scroll',
            bgRepeat: 'repeat',
            bgSizeWidth: 0,
            currentTheme: null,
          },
          {
            bgImg: [],
            bgPos: 'center center',
            bgSize: 'auto',
            pgColor: {
              type: 'pure',
              angle: 90,
              active: 0,
              colors: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              values: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              trigger: false,
              linearangle: [0, 100],
              linearcolor: ['#777777', '#000000'],
            },
            bgAttach: 'scroll',
            bgRepeat: 'repeat',
            bgSizeWidth: 0,
            currentTheme: null,
          },
          {
            bgImg: [],
            bgPos: 'center center',
            bgSize: 'auto',
            pgColor: {
              type: 'pure',
              angle: 90,
              active: 0,
              colors: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              values: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              trigger: false,
              linearangle: [0, 100],
              linearcolor: ['#777777', '#000000'],
            },
            bgAttach: 'scroll',
            bgRepeat: 'repeat',
            bgSizeWidth: 0,
            currentTheme: null,
          },
          {
            bgImg: [],
            bgPos: 'center center',
            bgSize: 'auto',
            pgColor: {
              type: 'pure',
              angle: 90,
              active: 0,
              colors: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              values: [
                '#1976d2',
                '#9c27b0',
                '#d32f2f',
                '#ed6c02',
                '#0288d1',
                '#2e7d32',
              ],
              trigger: false,
              linearangle: [0, 100],
              linearcolor: ['#777777', '#000000'],
            },
            bgAttach: 'scroll',
            bgRepeat: 'repeat',
            bgSizeWidth: 0,
            currentTheme: null,
          },
        ],
        hdFooter: false,
        hdHeader: false,
        pgContSize: 1,
        pgIndLayout: true,
        pgLayoutStyle: 2,
      },
    },
  ],
};
